name: final-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - openpyxl
  - jupyter
  - statsmodels
  - pip
  - wordcloud
